### ISSUE TITLE
Filtered event variant annotation table refinement

### ISSUE THREAD

**Issue by asd1289** [mskilab-org/case-report#14]
These are tasks to refine the filtered event table based on feedback from Marcin:

Responsibilities:

Clean-up and aesthetics:
@xanthopoulakis will work on the following:
1. Column order for the filtered table. Proposed order: 
Gene | Variant | Type | Tier | Dosage | Location
2. Color scheme to highlight tier 1 and 2 events. The order of tier importance 1 > 2 > 3. Perhaps use OncoKB schema

Multiplicity tasks:
@xanthopoulakis and @jrafailov will work on:
1. Add ALT/REF/VAF counts for dosage tool tip
2. @jrafailov will do a sanity check to see if the Dosage is > CN more than just chance
3. Subclonal tag/highlight may be based on the HMF cutoff from https://github.com/hartwigmedical/hmftools/blob/master/purple/README.md

OncoKB consolidation for all variant types:
1. @asd1289 test and finalize CN annotations
2. @asd1289 Add TSG/Onco label for the variant table
3. @kevinmhadi consolidate SV/fusion annotation
4. @asd1289 and @kevinmhadi consolidate all variant annotations
5. <nice to have> @asd1289 and @kevinmhadi add gain/loss of function tag from oncoKB

**Comment by jrafailov** [comment]
@xanthopoulakis New mutations.jsons are now deposited for NYU clinical samples.

You will see a distinct annotation field separated by `; ` and parsed to display the existing tooltip within the Mutations Multiplicity track. Hover track specification is as follows where [annotation] indicates the field is coming from the annotation string in the .json: 

Locus: `chromosome`: `startPoint`-`endPoint`
CN: `y`
Gene: `[annotation]Gene`
Filter: `[annotation]Filter`
Variant:  `[annotation]Protein_variant`,  `[annotation]Variant`, `[annotation]Genomic_variant`
TUMOR ALT | REF | TOTAL | VAF: `[annotation]Alt_count` | `[annotation]Ref_Count` | `[annotation](Alt_count + Ref_Count)` | `[annotation]((Alt_count ) / Alt_Count + Ref_count)`
NORMAL ALT | REF | TOTAL: `[annotation]Normal_alt_count` | `[annotation]Normal_ref_Count`| `[annotation](Normal_alt_count + Normal_ref_Count) `
OncoKB Oncogenicity: `[annotation]Oncogenicity` (IF NOT NA)
OncoKB Predicted Effect: `[annotation]Effect` (IF NOT NA)
OncoKB Therapeutic Level: `[annotation]Level` (IF NOT NA)

**Comment by jrafailov** [comment]
@xanthopoulakis 

I propose we stick to three shapes for the mutations track. As "color" is interpolated from the field `col` in any supplied .json for any track, ideally we would keep the same paradigm for shape so that we could manipulate it simply on the backend. Would this be possible? 

Looking at the [shape database you sent earlier](https://vega.github.io/vega/docs/marks/symbol/), circle is appropriate for our default. I propose we use the triangle shape for any mutations passed to OncoKB (in its geneset). And lastly we label those with a predicted Oncogenic effect as a star (the last shape in the dropdown menu).

**Comment by kevinmhadi** [comment]
Here's the update on the points so far:

> 
> **1. @asd1289 test and finalize CN annotations (DONE)
> 2. @asd1289 Add TSG/Onco label for the variant table (DONE)**
> _3. @kevinmhadi consolidate SV/fusion annotation (TODO)_
> **4. @asd1289 and @kevinmhadi consolidate all variant annotations (DONE)
> 5. @asd1289 and @kevinmhadi add gain/loss of function tag from oncoKB (DONE)**
> 

**Points (1) and (4)**: OncoKB processing pipeline now can take in multiplicity, jabba (or facets converted gGraph for PACT), and fusions.

**Points (2) and (5):**
New OncoKB columns for filtered events
`role`: TSG/Oncogene 
`effect`: "Gain of function or loss of function status
`ref`: (maf only), REF counts
`alt`: (maf only), ALT counts
`VAF`: (maf only)
`segment_cn`: (maf only), total segmental copies (from jabba/facets)
`total_copies`: (maf only), estimated multiplicity

Skilift branch is updated with parsers for oncokb cna, fusions, and maf files for the filtered events. The above additional columns have also been incorporated into skilift for downstream [oncokb_fusions](https://github.com/mskilab-org/skilift/commit/9243e0997562a2e82a842b0965b091cdbe0a65d8)

The latest outputs (see columns below) are in pairs table:
`"/gpfs/data/imielinskilab/projects/Clinical_NYU/db/pairs.20241119_105207.rds"`

These are the relevant outputs.
WGS: `oncokb_maf`, `oncokb_fusions` , `oncokb_cna`
PACT: `oncokb_cna_pact`, `oncokb_maf_pact`

**Point (3)**: Non-fusion SV annotations still needs work, and probably won't be happening until after this sprint. This will be on the backburner.

Adding in cytoband and the exon should be easy to fusions, but that will be in the next update (hopefully by tomorrow).

**Comment by shihabdider** [comment]
@kevinmhadi The updated `oncokb_cna` is breaking because of a missing `min_cn` column. Was this removed?

N.B I have pushed newer tests to a `filtered_events_tests` branch (this has the `oncokb_fusions` branch merged already). You can work and run tests in this branch. Note that there has been a name change `oncotable.R -> filtered-events.R` (likewise for the test file). 

```
9: eval(jsub, SDenv, parent.frame())
8: eval(jsub, SDenv, parent.frame())
7: `[.data.table`(oncokb_cna, , .(gene = HUGO_SYMBOL, role = Role, 
       value = min_cn, type = ifelse(ALTERATION == "Amplification", 
           "amp", ifelse(ALTERATION == "Deletion", "homdel", NA_character_)), 
       tier = tier, tier_description = tier_factor, therapeutics = tx_string, 
       resistances = rx_string, diagnoses = dx_string, prognoses = px_string, 
       effect = MUTATION_EFFECT, track = "scna", source = "oncokb_cna")) at filtered-events.R#
302
6: oncokb_cna[, .(gene = HUGO_SYMBOL, role = Role, value = min_cn, 
       type = ifelse(ALTERATION == "Amplification", "amp", ifelse(ALTERATION == 
           "Deletion", "homdel", NA_character_)), tier = tier, tier_description = tier_factor,
 
       therapeutics = tx_string, resistances = rx_string, diagnoses = dx_string, 
       prognoses = px_string, effect = MUTATION_EFFECT, track = "scna", 
       source = "oncokb_cna")] at filtered-events.R#302
5: collect_oncokb_cna(oncokb_cna, verbose)
4: lapply(list(...), function(x) if (is.list(x)) x else as.data.table(x))
3: rbind(deparse.level, ...)
2: rbind(out, collect_oncokb_cna(oncokb_cna, verbose), fill = TRUE, 
       use.names = TRUE) at filtered-events.R#563
1: oncotable(pair = row$pair, somatic_variant_annotations = row$somatic_variant_annotations, 
       fusions = row$fusions, jabba_gg = row$jabba_gg, karyograph = row$karyograph, 
       events = row$events, signature_counts = row$signature_counts, 
       oncokb_snv = row$oncokb_snv, oncokb_cna = row$oncokb_cna, 
       gencode = gencode, verbose = TRUE, amp.thresh = 2, filter = "PASS", 
       del.thresh = 0.5)
```

**Comment by kevinmhadi** [comment]
Missing `min_cn` field in `oncokb_cna` outputs is fixed now.

**Comment by kevinmhadi** [comment]
Added `variant_summary`, `gene_summary`, and `mutation_effect_description` to oncokb outputs
Skilift branch: [oncokb_fusions](https://github.com/mskilab-org/skilift/commit/9243e0997562a2e82a842b0965b091cdbe0a65d8)

These are curated, oncokb descriptions of the gene, variant, and mutation effect that can be place in the tiering modal, or as a starter for a static report.

**Comment by shihabdider** [comment]
Clinical samples have been updated with new oncokb tiered filtered events:
https://genome.med.nyu.edu/external/imielinskilab/mskiweb/xanthc01/case-report/?location=1:1-M:16571&dataset=clinical-samples

I have pushed all changes to main. Please prune old branches and branch from the new main. (edited)

**Comment by shihabdider** [comment]
## Specification for Front-End Changes to Filtered Events Table

### Example of New `filtered.events.json`
Sourced from: https://genome.med.nyu.edu/external/imielinskilab/mskiweb/diders01/case-reports-clinical-backup/build/data/397089/filtered.events.json
```json
[
  {
    "gene": "DCDC2",
    "vartype": "fusion",
    "type": "fusion",
    "Tier": "3",
    "effect": "Unknown",
    "fusion_genes": "DCDC2,RGL1",
    "fusion_gene_coords": "6:24171984-24358280-,1:183605220-183897665+",
    "Variant": "Total CN:6.739; CN Minor:1; CN Major:5.739",
    "Genome_Location": "6:24171984-24358280",
    "id": "397089",
    "seqnames": "6",
    "start": "24171984",
    "end": "24358280"
  },
  {
    "gene": "KRAS",
    "gene_summary": "KRAS, a GTPase which functions as an upstream regulator of the MAPK pathway, is frequently mutated in various cancer types including lung, colorectal and pancreatic cancers.",
    "role": "Oncogene",
    "vartype": "SNV",
    "type": "missense",
    "Tier": "1",
    "variant_summary": "The KRAS G12C mutation is known to be oncogenic.",
    "therapeutics": "Adagrasib+Cetuximab,Sotorasib,Adagrasib,Adagrasib+Panitumumab,Cobimetinib,Sotorasib+Cetuximab,Trametinib,Sotorasib+Panitumumab",
    "resistances": "Cetuximab,Panitumumab,Tucatinib+Trastuzumab",
    "effect": "Gain-of-function",
    "effect_description": "The KRAS G12C mutation is located in the P-loop of the catalytic G-domain of the protein. This mutation has been found in lung and colorectal cancer (PMID: 28572459). Expression of this mutation in lung and breast cancer cell lines and mouse models demonstrated that it is activating, as measured by increased pathway activation, cell proliferation, colony formation and in vivo tumor formation compared to wildtype (PMID: 25705018, 26841430, 16051643, 32792368). In vitro studies of cells expressing the KRAS G12C mutation demonstrate that it is sensitive to several targeted therapies designed specifically for this allele, including ARS853 (PMID: 26841430, 24256730). In a phase I clinical trial of the KRAS G12C inhibitor AMG510 in which thirteen patients with non-small cell lung cancer harboring this mutation were given the target drug dose, 100% of patients responded, with seven patients having partial response and six patients having stable disease (Abstract: Fakih et al. Abstract# 3003, ASCO 2019. https://meetinglibrary.asco.org/record/172411/abstract). KRAS G12C has been identified as an acquired resistance mutation in two patients with EGFR-mutated non-small cell lung cancer following a durable response to osimertinib (PMID: 38096473).",
    "Variant_g": "g.25398285-25398285",
    "Variant": "Gly12Cys",
    "total_copies": "2.78816131894441",
    "segment_cn": "3",
    "ref": "26",
    "alt": "49",
    "VAF": "0.653333333333333",
    "Genome_Location": "12:25357723-25403870",
    "id": "397089",
    "seqnames": "12",
    "start": "25357723",
    "end": "25403870"
  }
]
```

### New Columns to be Added to Events Table:
- `role`: Displays whether the gene is a Tumor Suppressor Gene (TSG) or an Oncogene.
- `effect`: Indicates the gain of function or loss of function status.
- `ref`: (maf only) Displays REF counts.
- `alt`: (maf only) Displays ALT counts.
- `VAF`: (maf only) Variant Allele Frequency.
- `segment_cn`: (maf only) Total segmental copies from jabba/facets.
- `total_copies`: (maf only) Previously called dosage, shows estimated multiplicity.

### New Information to be Displayed in the Events Modal:
- `variant_summary`: Provides a summary of the variant.
- `gene_summary`: Provides a summary of the gene.
- `mutation_effect_description`: Describes the effect of the mutation.

### Additional Notes:
- For `fusion_gene_coords`, remove the trailing strand (+/-) from the coordinates for opening in split view.
- Note some entries have missing columns, code should be robust to this
- All attribute values were coerced to string, including numbers -- still working on this, but it seems like the code is already robust to it

**Comment by xanthopoulakis** [comment]
@shihabdider in which order should these columns be added?
<img width="627" alt="image" src="https://github.com/user-attachments/assets/9a4bc22e-6979-4247-917f-85718f750114">
I mean now we have Gene | Variant | Type | Tier | Dosage | Location

Where are these columns expected to be placed? Perhaps between Dosage and Location?

**Comment by kevinmhadi** [comment]
I think the order should be:

Gene | Role | Variant | Type | Effect | Tier | Total_Copies | REF | ALT | VAF | segment_CN | Location

@asd1289 What do you think?

**Comment by jrafailov** [comment]
can we put total_copies between VAF / segment_CN?

**Comment by jrafailov** [comment]
also switch ALT/REF order? to make analogous to hover view in casereports

**Comment by xanthopoulakis** [comment]
So, what should the final order of columns be, can you please repost @kevinmhadi ?

**Comment by shihabdider** [comment]
@xanthopoulakis see:
 
> ### New Columns to be Added to Events Table:

> * `total_copies`: (maf only) Previously called `dosage`, shows estimated multiplicity.

**Comment by jrafailov** [comment]
total_copies - "Altered Copies"
segment_cn - "Total Copies"

this will probably cause confusion down the line but.. good for now?

**Comment by xanthopoulakis** [comment]
@shihabdider , so I updated some relevant changes on the NYU instance, namely:
1: Estimated Altered Copies column title is now Altered Copies
<img width="1716" alt="image" src="https://github.com/user-attachments/assets/39e70506-946b-4766-a9c0-4c64316e0cf2">

2: Centering for vartype DEL also works now 
<img width="1707" alt="image" src="https://github.com/user-attachments/assets/694ebdde-c91c-43d5-b803-c370ca615386">

3. The filtered events table has now quite a number of columns so smaller screens may suffer. I believe the requirement was to have Case Report render appropriately at minimum on 16 inch monitors 
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/59301102-421f-45aa-ba6f-8b12117a6a10">

**Comment by shihabdider** [comment]
> @xanthopoulakis
> 
> Minor revisions:
> 
> Can the filtered table be adjusted so that it is ordered as follows? `Gene | Role | Variant | Type | Effect | Tier | estimated_altered_copies | segment_CN | ALT | REF | VAF | Location`
> 
> As all entries are guaranteed to have estimated_altered_copies/segment_CN, I propose we feature them first (before alt/ref/vaf)? @kevinmhadi @asd1289 @shihabdider thoughts?
> 
> Also I think "No REF Counts value available", etc. is potentially too verbose? Could we replace with a simple "-" or a grayed & italicized "NA"?

`NA` is probably good. `-` could mean too many things.

**Comment by shihabdider** [comment]
A remaining issues:

- SNPs are still not being centered

![image](https://github.com/user-attachments/assets/eb6ac326-25df-4abe-ae8a-2dcc11542936)

- The `effect` and `effect_description` should also be in the events modal (if available for that event) -- I suspect the name of the attribute is being incorrectly called (probably `mutation_effect_description` instead of `effect_description`) which is the `Mutation Effect` field is NA.

![image](https://github.com/user-attachments/assets/57bc0bc5-9998-4bdc-8304-89697e68ff14)

**Comment by xanthopoulakis** [comment]
@shihabdider , should we be centering on the star or the gene?

**Comment by xanthopoulakis** [comment]
@shihabdider , I uploaded the latest fixes yesterday with respect to zeros appearing as NA on the filtered events table. Please feel free to review the latest state of the table and add your comments in here.

**Comment by shihabdider** [comment]
Looks good!

Just a few more minor revisions:

- the metdata header also seems to be interpreting some zeros (particularly the HRD score) as NA
![image](https://github.com/user-attachments/assets/246cc783-54bf-4b8e-a7da-1e29deb64bb0)
![image](https://github.com/user-attachments/assets/64471bf3-04e1-47a6-9849-977e13c2a495)
- total segmental copies should also be truncated to 3 decimals -- although based on the discussion yesterday we might change this column entirely(?): 
![image](https://github.com/user-attachments/assets/b0dfaee7-0429-40d1-af42-743a592987e3)
- add a horizontal scrollbar to the filtered events component, that way it doesn't break the UI on smaller screens:
![image](https://github.com/user-attachments/assets/f98cd919-5a09-49fe-8eaf-d021e26c887a)

A more extensive change (probably worth its own issue) is to separate out SCNA, SNV and fusions into separate tabs on the filtered events. Each tab would have a slightly different set of columns. This would allow us to remove some columns that otherwise would always be NA for certain classes of events. (Kudos to @asd1289 for the idea).

**Comment by xanthopoulakis** [comment]
@shihabdider , i have pushed my latest changes addressing the items you mention, please feel free to verify

**Comment by shihabdider** [comment]
I think we can close this issue for now. Can always reopen it again if we come back to this on a future sprint.
