### ISSUE TITLE
centering on locus upon click and have gene be included in full module upon click

### ISSUE THREAD

**Issue by jrafailov** [mskilab-org/case-report#17]
**Describe the bug**
@shihabdider had implemented this before but it seems that this functionality is no longer working. 
The expected behavior is from the filtered events table, upon click the module that comes up should center around the locus position indicated by the table. Additionally, the full gene range should be visible + some padding!

**To Reproduce**
1. click on mutation in events table
2. note that module appears but not centered where locus is

**Expected behavior**
The expected behavior is from the filtered events table, upon click the module that comes up should center around the locus position indicated by the table. Additionally, the full gene range should be visible + some padding!

**Comment by shihabdider** [comment]
Ah, I think I see the problem. 

It's relying on `vartype == "SNV"` to enforce the centering, but the oncokb snv outputs omit this field (we should probably fix this @kevinmhadi ). @xanthopoulakis an easy fix is to instead check if `["missense",  "trunc"].includes(type)` as the condition.

**Comment by kevinmhadi** [comment]
I just pushed the change to Skilift branch `oncokb_fusions` to add `vartype = "SNV"` for all small mutations from oncokb (I'm assuming indels are flagged the same way)

**Comment by shihabdider** [comment]
Great, then @xanthopoulakis you don't need to make any changes. I just have to update the filtered events table.

**Comment by shihabdider** [comment]
@xanthopoulakis Unfortunately, it doesn't seem like adding `vartype` fixed this issue. I would double check how the `Location` column is being populated. I suspect the old methods are being overridden by new code that you introduced in your refactor.

> See:
> 
> https://github.com/mskilab-org/case-report/blob/9a3ca30087c1f81ad3fe00b652608150638d4b38/src/helpers/utility.js#L833
> 
> The method is still there, but I think it's not longer being used?

**Comment by shihabdider** [comment]
OK after further investigation, it seems like the `Variant_g` is no longer being reported as expected with the new oncokb calls: (e.g `"Variant_g": "g.25398285-25398285",`). Previously `Variant_g` had the base change and the coordinates formatted as `seqname:start-end`. This is why it's not working. 

@kevinmhadi Any chance we can update the `Variant_g` in the `onckob_snv` to reflect the old format? (e.g `"Variant_g": "2:29432664-29432664 C>T",`)

For the fusions, the behavior is a bit weird. For some fusions it opens in split:

![image](https://github.com/user-attachments/assets/bf6d2f69-4715-4812-bcd9-258b3c12d9b6)

For others it doesn't:

![image](https://github.com/user-attachments/assets/a36401ec-2573-4f18-be59-4f26d5a3120a)

**Comment by shihabdider** [comment]
OK, so centering for `vartype==SNV` now works again. However, this centering code should also apply to DELs.

@xanthopoulakis you just need to update this line https://github.com/mskilab-org/case-report/blob/9a3ca30087c1f81ad3fe00b652608150638d4b38/src/helpers/utility.js#L848 

to include `DEL`, i.e the condition should be `vartype == "SNV" || vartype == "DEL"`
