### ISSUE TITLE
Column names for various event types

### ISSUE THREAD

**Issue by asd1289** [mskilab-org/case-report#19]
The event types to be separated in three types separated by types. Following are suggested column names for each:

1. SNV: the columns remain the same as we have right now.
2. CNV: Gene | Role in Cancer | Variant | Type | Effect | Tier | Total Segmental Copies | Location
3. Fusions: Gene | Role in Cancer | Variant | Type | Effect | Tier | Total Fusion Copies | Location

Hide Tier 3 calls.

@kevinmhadi can elaborate on the "total fusion copies" column and any other fusion related details.

**Comment by kevinmhadi** [comment]
Yes, total fusion copies column should be the output from (`value =
min_cn`) from the oncokb_fusions output.

I think the other changes were to move the exon and cytoband information
out of the column into a tooltip. Although we are linking to the tier modal
in the gene names but would a tooltip on hover be possible for fusion
events?

**Comment by asd1289** [comment]
@xanthopoulakis 

Minor points of changes to the table:
1. Tabs:
> Change "CNV" tab to "CNA" tab and add all events with type "SCNA"
> For fusions, all events marked 'fusions"
> Rest all SNVs
3. Grey the tabs without any events 
4. Counts of events found to be displayed
5. Search bar for genes that autocomplete gene names
6. Hide Tier 3 events
7. Columns specific for each tab as described in this ticket (above)

**Comment by xanthopoulakis** [comment]
@asd1289 , please feel free to review

**Comment by shihabdider** [comment]
Just adding the suggestion from today's clinical meeting to include an `all` tab as well.

**Comment by asd1289** [comment]
I think I am going to close this for now. We can re-open if Marcin wants something else in there. Great job all!
