### ISSUE TITLE
hetsnps.arrow and mutations.json

### ISSUE THREAD

**Issue by stanleyrc** [mskilab-org/case-report#23]
The pan genome tab and the pop up crash case reports when the mutations.json and hetsnps.arrow are not present. Could it be adjusted such that it checks if they exist and does not show them if they do not exist?

**Comment by xanthopoulakis** [comment]
Could you please send me a link to the case report where you see this problem appearing? I have added a mechanism to check if the hetsnps.arrow or the mutations.json file is missing so that the application is not crushing. Any example?

**Comment by xanthopoulakis** [comment]
![image](https://github.com/user-attachments/assets/b760e7ca-27d0-4e7c-96ef-e9560e2d91a4)
@stanleyrc , I have added a patch which should now address the issue with the missing arrow files and showing an error message instead. Please feel free to give it a try:
http://mskiweb/cxanthopoulakis/case-report/?location=1:75392103-1:75403942&dataset=MelanomaC&report=test_missing_jsons&tab=2

**Comment by xanthopoulakis** [comment]
@stanleyrc , please review if this is still an issue, I believe the latest patch should have solved it. Then perhaps we can close the issue.

**Comment by stanleyrc** [comment]
The recent changes have fixed the issue! Thank you!
