### ISSUE TITLE
Plot components loading empty of data

### ISSUE THREAD

**Issue by shihabdider** [mskilab-org/case-report#5]
**Describe the bug**
![image](https://github.com/user-attachments/assets/e00d4990-0ce2-49c7-8d55-c369f8a464cb)
![image](https://github.com/user-attachments/assets/f833582a-b040-4967-bfbc-7abb611315db)

**To Reproduce**
There are a few ways to reproduce this error. The simplest is to just refresh on the pan-genome view tab. Also, switching to a different tab and then switching back will cause some of the plots to render without data (see 2nd image above).

**Expected behavior**
There should be some indication to the user that the data is loading (e.g a loading wheel, or better: a loading bar with progress). Components that are missing data should display an empty placeholder (similar to the placeholder for filtered events)

**Comment by xanthopoulakis** [comment]
This has proved a tricky one, I need to delve deeper to get down to the bottom of it

**Comment by xanthopoulakis** [comment]
@shihabdider , can we perhaps check if this is still an issue? I have added some patches on the server, perhaps we can check

**Comment by shihabdider** [comment]
Confirmed fixed. Nice work @xanthopoulakis !
