### ISSUE TITLE
Copy number axis are not being displayed properly

### ISSUE THREAD

**Issue by shihabdider** [mskilab-org/case-report#8]
**Describe the bug**
https://genome.med.nyu.edu/external/imielinskilab/mskiweb/xanthc01/case-report/?dataset=clinical-samples&tab=2&report=1160696&location=1:1-M:16571
![image](https://github.com/user-attachments/assets/fe32603e-f8f6-4ad9-8d7a-2b02de732a89)

**To Reproduce**
Open pan-genome view, then switch to another tab or patient. Once you get past #5 the left axis are all missing for the plots that do load and the right axis overlaps with the plot making it difficult to read.

**Expected behavior**
Bot axis should be visible and non-overlapping.

**Additional context**
Most likely related to #5 since the axis will appear on the initial load but disappears after changing patient or tab state.

**Comment by xanthopoulakis** [comment]
@shihabdider , I have added a warning notification on the scatterplots header to indicate when the slope and intercept attributes are missing from the metadata.json file, which may cause the left hand axis not rendering 
![image](https://github.com/user-attachments/assets/b8edbc95-a4f6-4e99-9990-a8874716b189)
